<?php
declare(strict_types=1);
function xlsx_col(int $n): string {$s='';$n++;while($n>0){$m=($n-1)%26;$s=chr(65+$m).$s;$n=intdiv($n-1,26);}return $s;}
function xlsx_xml(string $s): string {return htmlspecialchars($s,ENT_XML1|ENT_QUOTES,'UTF-8');}
function xlsx_download(array $rows,string $filename): never {
 if(!class_exists('ZipArchive'))throw new RuntimeException('ZipArchive mangler på webhotellet, så XLSX kan ikke oprettes. Brug CSV-eksporten som alternativ.');
 $tmp=tempnam(sys_get_temp_dir(),'hsgxlsx');$zip=new ZipArchive();if($zip->open($tmp,ZipArchive::OVERWRITE)!==true)throw new RuntimeException('Kunne ikke oprette Excel-filen.');
 $types='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>';
 $rels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';
 $wbrels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>';
 $wb='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Lager" sheetId="1" r:id="rId1"/></sheets></workbook>';
 $styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs></styleSheet>';
 $sheet='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>';
 foreach($rows as $ri=>$row){$rn=$ri+1;$sheet.='<row r="'.$rn.'">';foreach(array_values($row) as $ci=>$v){$ref=xlsx_col($ci).$rn;$style=$ri===0?' s="1"':'';if(is_int($v)||is_float($v))$sheet.='<c r="'.$ref.'"'.$style.'><v>'.$v.'</v></c>';else$sheet.='<c r="'.$ref.'" t="inlineStr"'.$style.'><is><t xml:space="preserve">'.xlsx_xml((string)$v).'</t></is></c>';}$sheet.='</row>';}$sheet.='</sheetData><autoFilter ref="A1:'.xlsx_col(max(0,count($rows[0]??[])-1)).max(1,count($rows)).'"/></worksheet>';
 $zip->addFromString('[Content_Types].xml',$types);$zip->addFromString('_rels/.rels',$rels);$zip->addFromString('xl/workbook.xml',$wb);$zip->addFromString('xl/_rels/workbook.xml.rels',$wbrels);$zip->addFromString('xl/styles.xml',$styles);$zip->addFromString('xl/worksheets/sheet1.xml',$sheet);$zip->close();
 header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9._-]+/','-',$filename).'"');header('Content-Length: '.filesize($tmp));readfile($tmp);@unlink($tmp);exit;
}
