<?php
require __DIR__.'/auth.php';require_module_enabled('locations');require_capability('locations.manage');
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{$action=$_POST['action']??'save';if($action==='save'){$id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$desc=trim($_POST['description']??'');$order=(int)($_POST['sort_order']??100);if($name==='')throw new RuntimeException('Lokationsnavn skal udfyldes.');if($id)$pdo->prepare('UPDATE lager_locations SET name=?,description=?,sort_order=? WHERE id=?')->execute([$name,$desc,$order,$id]);else{$pdo->prepare('INSERT INTO lager_locations(name,description,sort_order,active) VALUES(?,?,?,1)')->execute([$name,$desc,$order]);$id=(int)$pdo->lastInsertId();}audit_log($pdo,'location.save','location',(string)$id,['name'=>$name]);flash('success','Lokation gemt.');redirect('locations.php');}if($action==='toggle'){$toggleId=(int)$_POST['id'];$pdo->prepare('UPDATE lager_locations SET active=1-active WHERE id=?')->execute([$toggleId]);audit_log($pdo,'location.toggle','location',(string)$toggleId);flash('success','Lokationstatus ændret.');redirect('locations.php');}}catch(Throwable $e){flash('error','Kunne ikke gemme lokationen. Navnet skal være unikt.');}
}
$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM lager_locations WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$rows=$pdo->query("SELECT l.*,COALESCE(SUM(s.quantity),0) physical FROM lager_locations l LEFT JOIN lager_stock s ON s.location_id=l.id GROUP BY l.id ORDER BY l.sort_order,l.name")->fetchAll();page_header('Lokationer');
?>
<div class="card"><h2><?=$edit?'Rediger lokation':'Opret lokation'?></h2><form method="post" class="inline"><?=csrf_field()?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=$edit['id']??0?>"><label>Navn<input name="name" required value="<?=h($edit['name']??'')?>" placeholder="Fx Lager Gert"></label><label>Beskrivelse<input name="description" value="<?=h($edit['description']??'')?>"></label><label>Sortering<input type="number" name="sort_order" value="<?=h($edit['sort_order']??100)?>"></label><button>Gem</button><?php if($edit):?><a class="button secondary" href="locations.php">Annuller</a><?php endif;?></form></div>
<div class="table-wrap"><table><thead><tr><th>Lokation</th><th>Beskrivelse</th><th>Fysisk lager</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $l):?><tr><td><strong><?=h($l['name'])?></strong></td><td><?=h($l['description'])?></td><td><?=$l['physical']?> stk.</td><td><span class="badge <?=$l['active']?'green':''?>"><?=$l['active']?'Aktiv':'Deaktiveret'?></span></td><td class="actions"><a class="button secondary" href="?edit=<?=$l['id']?>">Rediger</a><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$l['id']?>"><button class="secondary"><?=$l['active']?'Deaktivér':'Aktivér'?></button></form></td></tr><?php endforeach;?></tbody></table></div>
<?php page_footer();
